version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./__docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - '8876:80'
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: ./__docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    container_name: project_app

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./__docker/mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports:
      - '8101:3306'
    container_name: project_db
